---
title: "Evaluate TF activity: repressions between TFs and targets"
author: "Koen Van den Berge"
date: "3/24/2020"
output: 
  html_document:
    toc: true
    toc_float: true
---


# Generate datasets

```{r, eval=FALSE}
library(tidyverse)
library(dyngen)

nIter <- 6
for(nn in 1:nIter){
  # generate a dataset
  set.seed(nn*10)
  backbone <- backbone_linear()
  model <- initialise_model(
    backbone = backbone,
    num_tfs = 100,
    num_targets = 500,
    num_hks = 100,
    tf_network_params = tf_network_default(sample_num_regulators = function() 2),
    feature_network_params = feature_network_default(max_in_degree=20),
    download_cache_dir = "~/.cache/dyngen",
    num_cores = 4,
    simulation_params = simulation_default(
      census_interval = 1,
      compute_cellwise_grn = TRUE
    )
  )
  dataset <- model %>%
    generate_tf_network() %>%
    generate_feature_network() %>%
    generate_kinetics() %>%
    generate_gold_standard() %>%
    generate_cells() %>%
    generate_experiment()
  
  saveRDS(list(model,dataset),
          file = paste0("datasets/simIters/dataset",nn,".rds"))
}

```


# One dataset

```{r}
library(msigdbr)
library(GSEABase)
library(viper)
library(AUCell)
library(tidyverse)
library(dyngen)
ksource <- function(x, ...) {
  library(knitr)
  source(purl(x, output = tempfile()), ...)
}
library(transfactor)
source('../simulateFromModel/20201120_evaluateSimulatedDataset.R')

data <- readRDS("datasets/simIters/dataset1.rds")
model <- data[[1]]
dataset <- data[[2]]

## plot
### Trajectory
library(dynplot)
wrappedDataset <- wrap_dataset(dataset)
# plots an MDS
# g1 <- dynplot::plot_dimred(wrappedDataset,
#             label_milestones = TRUE,
#             size_cells = 1,
#             size_trajectory = 2)

### GRN
g2 <- plot_backbone_modulenet(dataset) + labs(title = "Backbone module reg. net.")
g3 <- plot_feature_network(dataset, show_targets = FALSE) +
            labs(title = "TF reg. net.")
g4 <- plot_feature_network(dataset) + labs(title = "TF + target reg. net.")

g <- patchwork::wrap_plots(g2, g3, g4, byrow = TRUE, ncol = 2, nrow = 2, 
                           widths = rep(1, 2), heights = rep(1, 2)) +
  patchwork::plot_annotation(tag_levels = "A")
# ggsave("../plots/simDataDyngen1Plots.pdf", g, width = 30, height = 15)



countsAll <- t(as.matrix(dataset$experiment$counts_premrna + dataset$experiment$counts_mrna))

# only look at TFs
feature_info <- dataset$feature_info
tf_info <- feature_info %>% filter(is_tf)
feature_network <- dataset$feature_network %>% mutate(name = paste0(from, "->", to))

### get true GRN
tf <- as.character(unique(feature_network$from))
targets <- as.character(unique(feature_network$to))

## full GRN including repressions
XAll <- matrix(0, nrow=length(targets), ncol=length(tf),
            dimnames=list(targets, tf))
for(tt in 1:ncol(XAll)){
  curTF <- tf[tt]
  curTFTargets <- as.character(feature_network[feature_network$from == curTF, "to"][[1]])
  curTFEffects <- feature_network[feature_network$from == curTF, "effect"][[1]]
  XAll[cbind(curTFTargets,curTF)] <- curTFEffects
}
#sort(colSums(abs(XAll))) ; sort(table(feature_network$from)[colnames(XAll)]) #should be same
XAll <- XAll[rowSums(abs(XAll))>0,]
XAll <- XAll[,colSums(abs(XAll))>0]
# remove TFs with only repressions
tfsWithOnlyRepression <- apply(XAll, 2, function(x){
  all(x == 0 | x == -1)
})
XAll <- XAll[,!tfsWithOnlyRepression]
barplot(table(rowSums(abs(XAll))))
barplot(table(colSums(abs(XAll))))

## alpha
alpha <- abs(XAll)
id <- as.matrix(cbind(dataset$feature_network[,2], dataset$feature_network[,1]))
keepId <- id[,1] %in% rownames(XAll) & id[,2] %in% colnames(XAll) & dataset$feature_network$effect == 1
id <- id[keepId,]
alpha[id] <- dataset$feature_network$strength[keepId]

# truth: only TFs from burn-in or modules.
truth <- data.frame(de=rep(1, ncol(XAll)),
                    row.names=colnames(XAll))
truth[grep(x=rownames(truth), pattern="Target|HK"),] <- 0


countsTfTargets <- countsAll[rownames(XAll),]

nNoiseEdges <- 500
nNoiseTFs <- 10
XNoisy <- addNoiseToGRN(X = XAll,
                       nNoiseTFs = nNoiseTFs,
                       nNoiseEdges = nNoiseEdges,
                       noiseProb = 3/nrow(XAll),
                       seed = 10)

# truth
truthNoisy <- rbind(truth, data.frame(de=rep(0, nNoiseTFs),
                                      row.names=paste0("noisyTF",1:nNoiseTFs)))

## filter if necessary
keepGene <- rowSums(abs(XNoisy)) > 0
counts <- countsTfTargets[keepGene,]
curAlpha <- alpha[keepGene,]
XNoisy <- XNoisy[keepGene,]
keepTF <- colSums(abs(XNoisy)) > 0
truthNoisy <- truthNoisy[keepTF,,drop=FALSE]

# get true alpha for noisy GRN
if(nNoiseTFs > 0){
  alphaTrueNoisy <- cbind(curAlpha, XNoisy[,(ncol(XAll)+1):(ncol(XAll)+nNoiseTFs)])
} else {
  alphaTrueNoisy <- curAlpha
}
XNoisy <- XNoisy[,keepTF]
alphaTrueNoisy <- alphaTrueNoisy[,keepTF]
alphaTrueNoisy[XNoisy == 0] <- 0
rownames(truthNoisy) <- colnames(XNoisy)
# viper regulon
regulonNoisy <- constructViperRegulon(XNoisy, alphaTrueNoisy)
# AUCell genesets
genesetsNoisy <- constructGenesets(XNoisy, alphaTrueNoisy)

qSteps <- 0.05
pt <- dataset$experiment$cell_info$sim_time
ptGroups <- Hmisc::cut2(pt, cuts = quantile(pt, prob=seq(0,1,by=qSteps)))
Xpt <- model.matrix(~0+ptGroups)
design <- Xpt
```    

# Over iterations

```{r}
benchmarkDistances <- function(emRes,
                               counts,
                               X,
                               U,
                               cellGroups = NULL,
                               contrast = "consecutive",
                               deId){
  simple_auc <- function(TPR, FPR){
    # function from https://blog.revolutionanalytics.com/2016/11/calculating-auc.html
    # inputs already sorted, best scores first 
    dFPR <- c(diff(FPR), 0)
    dTPR <- c(diff(TPR), 0)
    sum(TPR * dFPR) + sum(dTPR * dFPR)/2
  }
  
  tfDistEuclid <- transfactor::tfDistance(activity = emRes,
                                    counts = counts,
                                    X = X,
                                    U = U,
                                    distance = "Euclidean",
                                    scaleDistance = FALSE,
                                    cellGroups = cellGroups,
                                    contrast = contrast)
  tfDistEuclidScaled <- transfactor::tfDistance(activity = emRes,
                                    counts = counts,
                                    X = X,
                                    U = U,
                                    distance = "Euclidean",
                                    scaleDistance = TRUE,
                                    cellGroups = cellGroups,
                                    contrast = contrast)
  tfDistL1 <- transfactor::tfDistance(activity = emRes,
                                    counts = counts,
                                    X = X,
                                    U = U,
                                 distance = "L1",
                                 scaleDistance = FALSE,
                                 cellGroups = cellGroups,
                                contrast = contrast)
  tfDistL1Scaled <- transfactor::tfDistance(activity = emRes,
                                    counts = counts,
                                    X = X,
                                    U = U,
                                    distance = "L1",
                                    scaleDistance = TRUE,
                                    cellGroups = cellGroups,
                                    contrast = contrast)
  tfDistEuclid_tf <- transfactor::tfDistance(activity = emRes,
                                    counts = counts,
                                    X = X,
                                    U = U,
                                    distance = "EuclideanTF",
                                    scaleDistance = FALSE,
                                    cellGroups = cellGroups,
                                    contrast = contrast)
  tfDistEuclidScaled_tf <- transfactor::tfDistance(activity = emRes,
                                    counts = counts,
                                    X = X,
                                    U = U,
                                    distance = "EuclideanTF",
                                    scaleDistance = TRUE,
                                    cellGroups = cellGroups,
                                    contrast = contrast)
  tfDistL1_tf <- transfactor::tfDistance(activity = emRes,
                                    counts = counts,
                                    X = X,
                                    U = U,
                                 distance = "L1TF",
                                 scaleDistance = FALSE,
                                 cellGroups = cellGroups,
                                contrast = contrast)
  tfDistL1Scaled_tf <- transfactor::tfDistance(activity = emRes,
                                    counts = counts,
                                    X = X,
                                    U = U,
                                    distance = "L1TF",
                                    scaleDistance = TRUE,
                                    cellGroups = cellGroups,
                                    contrast = contrast)
  tfDistRank <- transfactor::tfDistance(activity = emRes,
                                    counts = counts,
                                    X = X,
                                    U = U,
                                    distance = "rank",
                                    scaleDistance = FALSE,
                                    cellGroups = cellGroups,
                                    contrast = contrast)

  ## Euclid
  ooF <- order(tfDistEuclid, decreasing = TRUE)
  tprEuclid <- cumsum(deId[ooF]) / sum(deId)
  fprEuclid <- cumsum(!deId[ooF]) / sum(!deId)
  auc_euclid <- simple_auc(tprEuclid, fprEuclid)
  ## Euclid scaled
  ooF <- order(tfDistEuclidScaled, decreasing = TRUE)
  tprEuclidScaled <- cumsum(deId[ooF]) / sum(deId)
  fprEuclidScaled <- cumsum(!deId[ooF]) / sum(!deId)
  auc_euclidScaled <- simple_auc(tprEuclidScaled, fprEuclidScaled)
  ## L1
  ooF <- order(tfDistL1, decreasing = TRUE)
  tprL1 <- cumsum(deId[ooF]) / sum(deId)
  fprL1 <- cumsum(!deId[ooF]) / sum(!deId)
  auc_l1 <- simple_auc(tprL1, fprL1)
  ## L1 scaled
  ooF <- order(tfDistL1Scaled, decreasing = TRUE)
  tprL1Scaled <- cumsum(deId[ooF]) / sum(deId)
  fprL1Scaled <- cumsum(!deId[ooF]) / sum(!deId)
  auc_l1Scaled <- simple_auc(tprL1Scaled, fprL1Scaled)
  ## Euclid TF
  ooF <- order(tfDistEuclid_tf, decreasing = TRUE)
  tprEuclid_tf <- cumsum(deId[ooF]) / sum(deId)
  fprEuclid_tf <- cumsum(!deId[ooF]) / sum(!deId)
  auc_euclid_tf <- simple_auc(tprEuclid_tf, fprEuclid_tf)
  ## Euclid scaled TF
  ooF <- order(tfDistEuclidScaled_tf, decreasing = TRUE)
  tprEuclidScaled_tf <- cumsum(deId[ooF]) / sum(deId)
  fprEuclidScaled_tf <- cumsum(!deId[ooF]) / sum(!deId)
  auc_euclidScaled_tf <- simple_auc(tprEuclidScaled_tf, fprEuclidScaled_tf)
  ## L1 TF
  ooF <- order(tfDistL1_tf, decreasing = TRUE)
  tprL1_tf <- cumsum(deId[ooF]) / sum(deId)
  fprL1_tf <- cumsum(!deId[ooF]) / sum(!deId)
  auc_l1_tf <- simple_auc(tprL1_tf, fprL1_tf)
  ## L1 scaled TF
  ooF <- order(tfDistL1Scaled_tf, decreasing = TRUE)
  tprL1Scaled_tf <- cumsum(deId[ooF]) / sum(deId)
  fprL1Scaled_tf <- cumsum(!deId[ooF]) / sum(!deId)
  auc_l1Scaled_tf <- simple_auc(tprL1Scaled_tf, fprL1Scaled_tf)
  ## ranks
  ooF <- order(tfDistRank, decreasing = TRUE)
  tprRank <- cumsum(deId[ooF]) / sum(deId)
  fprRank <- cumsum(!deId[ooF]) / sum(!deId)
  auc_rank <- simple_auc(tprRank, fprRank)
  
  
  # par(bty='l')
  # plot(x=fprEuclid, y=tprEuclid, type='l', col="black", xlab="FPR", ylab="TPR")
  # lines(x=fprEuclidScaled, y=tprEuclidScaled, col="orange")
  # lines(x=fprL1, y=tprL1, col="darkseagreen3")
  # lines(x=fprL1Scaled, y=tprL1Scaled, col="steelblue")
  # legend("bottomright", c("Euclid", "Euclid scaled", "L1", "L1 scaled"),
  #        lty = 1, col=c("black", "orange", "darkseagreen3", "steelblue"),
  #        bty="n")
  aucs <- c(auc_euclid, auc_euclidScaled, auc_l1, auc_l1Scaled,
            auc_euclid_tf, auc_euclidScaled_tf, auc_l1_tf, auc_l1Scaled_tf,
            auc_rank)
  names(aucs) <- c("Euclid", "Euclid scaled", "L1", "L1 scaled",
                   "Euclid tf", "Euclid scaled tf", "L1 tf", "L1 scaled tf",
                   "ranks")
  return(aucs)
}
```



```{r}
nNoiseTFGrid <- c(0, ncol(XAll), ncol(XAll)*2, ncol(XAll)*4) # 100% to 33.3% data-generating TFs
nNoiseEdgeGrid <- c(-sum(abs(XAll))/2, -sum(abs(XAll))/4, 0, sum(abs(XAll))*2, sum(abs(XAll))*4) # -50% to +200% true links
nIter <- 3
#dfAUCAll <- readRDS("dfAUCAll_dyngen4.rds")


pNoLeg <- list()
for(nn in 1:nIter){
  # load a dataset
  set.seed(nn*10)
  data <- readRDS(paste0("datasets/simIters/dataset",nn,".rds"))
  model <- data[[1]]
  dataset <- data[[2]]
  
  for(nnTF in 1:length(nNoiseTFGrid)){
    nNoiseTFs <- nNoiseTFGrid[nnTF]
    for(nnEdge in 1:length(nNoiseEdgeGrid)){
      nNoiseEdges <- nNoiseEdgeGrid[nnEdge]
      countsAll <- t(as.matrix(dataset$experiment$counts_premrna + dataset$experiment$counts_mrna))
      
      # only look at TFs
      feature_info <- dataset$feature_info
      tf_info <- feature_info %>% filter(is_tf)
      feature_network <- dataset$feature_network %>% mutate(name = paste0(from, "->", to))
      
      ### get true GRN
      tf <- as.character(unique(feature_network$from))
      targets <- as.character(unique(feature_network$to))
      
      ## full GRN including repressions
      XAll <- matrix(0, nrow=length(targets), ncol=length(tf),
                  dimnames=list(targets, tf))
      for(tt in 1:ncol(XAll)){
        curTF <- tf[tt]
        curTFTargets <- as.character(feature_network[feature_network$from == curTF, "to"][[1]])
        curTFEffects <- feature_network[feature_network$from == curTF, "effect"][[1]]
        XAll[cbind(curTFTargets,curTF)] <- curTFEffects
      }
      XAll <- XAll[rowSums(abs(XAll))>0,]
      XAll <- XAll[,colSums(abs(XAll))>0]
      # remove TFs with only repressions
      tfsWithOnlyRepression <- apply(XAll, 2, function(x){
        all(x == 0 | x == -1)
      })
      XAll <- XAll[,!tfsWithOnlyRepression]
      barplot(table(rowSums(abs(XAll))))
      barplot(table(colSums(abs(XAll))))
      
      ## alpha
      alpha <- abs(XAll)
      id <- as.matrix(cbind(dataset$feature_network[,2], dataset$feature_network[,1]))
      keepId <- id[,1] %in% rownames(XAll) & id[,2] %in% colnames(XAll) & dataset$feature_network$effect == 1
      id <- id[keepId,]
      alpha[id] <- dataset$feature_network$strength[keepId]
      
      # truth: only TFs from burn-in or modules.
      truth <- data.frame(de=rep(1, ncol(XAll)),
                          row.names=colnames(XAll))
      truth[grep(x=rownames(truth), pattern="Target|HK"),] <- 0
      
      
      countsTfTargets <- countsAll[rownames(XAll),]
      
      XNoisy <- addNoiseToGRN(X = XAll,
                             nNoiseTFs = nNoiseTFs,
                             nNoiseEdges = nNoiseEdges,
                             noiseProb = 3/nrow(XAll))
      
      # truth
      truthNoisy <- rbind(truth, data.frame(de=rep(0, nNoiseTFs)))
      ## filter if necessary
      keepGene <- rowSums(abs(XNoisy)) > 0
      counts <- countsTfTargets[keepGene,]
      curAlpha <- alpha[keepGene,]
      XNoisy <- XNoisy[keepGene,]
      keepTF <- colSums(abs(XNoisy)) > 0
      truthNoisy <- truthNoisy[keepTF,,drop=FALSE]
      
      # get true alpha for noisy GRN
      if(nNoiseTFs > 0){
        alphaTrueNoisy <- cbind(curAlpha, XNoisy[,(ncol(XAll)+1):(ncol(XAll)+nNoiseTFs)])
      } else {
        alphaTrueNoisy <- curAlpha
      }
      XNoisy <- XNoisy[,keepTF]
      alphaTrueNoisy <- alphaTrueNoisy[,keepTF]
      alphaTrueNoisy[XNoisy == 0] <- 0
      rownames(truthNoisy) <- colnames(XNoisy)
     
      
      qSteps <- 0.05
      ptGroups <- Hmisc::cut2(pt, cuts = quantile(dataset$experiment$cell_info$sim_time, prob=seq(0,1,by=qSteps)))
      Xpt <- model.matrix(~0+ptGroups)
      design <- Xpt
          
      poisLassoRes <- transfactor::estimateActivity(counts = countsAll,
                                      X = XNoisy,
                                      model = "poisson",
                                      U = design,
                                      verbose = FALSE,
                                      plot = FALSE,
                                      maxIter = 500,
                                      epsilon=.1,
                                      sparse = TRUE,
                                      repressions = TRUE)
      
      ## remove TFs with only repressions
      ## TFs with repressions
      reprTF = apply(XNoisy, 2, function(x) any(x == -1))
      ## TFs with also positive interactions
      reprTFPos = apply(XNoisy[,reprTF], 2, function(x) any(x == 1))
      onlyRepressingTFs <- which(reprTF)[!reprTFPos]
      if(length(onlyRepressingTFs) > 0){
        curAUC <- benchmarkDistances(emRes = poisLassoRes,
                     counts = countsAll,
                     X = XNoisy[,-onlyRepressingTFs],
                     U = design,
                     contrast = "consecutive",
                     deId = truthNoisy[-onlyRepressingTFs,1])
      } else {
        curAUC <- benchmarkDistances(emRes = poisLassoRes,
                     counts = countsAll,
                     X = XNoisy,
                     U = design,
                     contrast = "consecutive",
                     deId = truthNoisy[,1])
      }
      
      curDfAUC <- data.frame(auc = curAUC,
                             method = names(curAUC),
                             noiseEdges = nNoiseEdges,
                             noiseTFs = nNoiseTFs)

      
      if(nn == 1 & nnEdge == 1 & nnTF == 1){
        dfAUCAll <- curDfAUC
      } else {
        dfAUCAll <- rbind(dfAUCAll, curDfAUC)
      }
      
    }
  }
  
  saveRDS(dfAUCAll, file=paste0("../objects/dfAUCAll_dyngen_distances_",nn,".rds"))
}


date <- Sys.Date()
date <- gsub(x=date, pattern="-", replacement="")
saveRDS(dfAUCAll, file=paste0("../objects/dfAUCAll_dyngen_distances",date,".rds"))
```


```{r}
dfAUCAll <- readRDS("../objects/dfAUCAll_dyngen_distances20210511.rds")
dfAUCAll$method <- factor(dfAUCAll$method, 
                          levels = c("Euclid", "Euclid tf",
                                     "Euclid scaled", "Euclid scaled tf",
                                     "L1", "L1 tf",
                                     "L1 scaled", "L1 scaled tf",
                                     "ranks"))

ggplot(dfAUCAll, aes(x=method, y=auc)) +
  geom_boxplot(aes(col=method)) +
  facet_wrap(.~noiseTFs * noiseEdges, 
             ncol = length(nNoiseEdgeGrid), 
             nrow = length(nNoiseTFGrid)) +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_y_continuous(n.breaks=4) +
  xlab("") + ylab("AUC")
ggsave("../plots/aucAllSettings_dyngen_distances.pdf", width=12, height=9)
```


