---
title: "GRN simulation: MSE"
author: "Koen Van den Berge"
date: "9/14/2020"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Simulation functions

```{r}
library(matrixStats)
ksource <- function(x, ...) {
  library(knitr)
  source(purl(x, output = tempfile()), ...)
}
library(tidyverse)
library(viper)
library(AUCell)
library(tidyverse)
library(GSEABase)
library(transfactor)

simulateFromGRN_extended <- function(X, 
                                   G=500, 
                                   nTF=80,
                                   fracDETFs=0.25,
                                   nPerGroup=50,
                                   nCellTypes=5, 
                                   shape_mu_t=1, 
                                   scale_mu_t=2, 
                                   shape_lambda_gc=1,
                                   scale_lambda_gc=scale_lambda_gc,
                                   magnitude_g=rep(100, G),
                                   seed=3,
                                   dirichletNoise = FALSE){
  
  set.seed(seed)
 
  ### Simulate mu_tc
  mu_tc <- matrix(rgamma(n=nTF, shape=shape_mu_t, scale=scale_mu_t),
                nrow=nTF, ncol=nCellTypes, byrow=FALSE)
  ### add noise
  # mu_tc_noise <- mu_tc + matrix(rnorm(n=length(mu_tc), mean=mu_tc, sd=.5),
  #                               nrow=nTF, ncol=nCellTypes)
  # mu_tc_noise[mu_tc_noise <= 0] <- 1e-5
  mu_tc_noise <- mu_tc
  rownames(mu_tc) <- paste0("tf",1:nTF)
  rownames(mu_tc_noise) <- paste0("tf",1:nTF)
  
  ### simulate DE
  deTFs <- sample(nTF, size=nTF * fracDETFs)
  # simulate fold changes
  logFC <- log(rnorm(n=length(deTFs) * (nCellTypes-1), mean=2.5, sd=.3))
  # random sign
  x <- rbinom(n=length(deTFs) * (nCellTypes-1), size=1, prob=.5)
  # logFC <- log(rep(5, length(deTFs) * (nCellTypes-1)))
  # x <- rep(1, length(deTFs) * (nCellTypes-1))
  fcAll <- matrix(1, nrow = nTF, ncol = nCellTypes - 1)
  fcAll[deTFs, ] <- matrix(exp(ifelse(x == 1, 1, -1) * logFC),
                           nrow = length(deTFs), ncol = nCellTypes - 1)
  mu_tc_noise[, -1] <- mu_tc_noise[, -1] * fcAll

  ### mu_gc
  mu_gc_sim <- X %*% mu_tc_noise
  
  ### calculate mu_gtc, mu_gc
  alpha_gt <- list()
  for(gg in 1:G){
    id <- which(X[gg,] == 1)
    mu_tc_id <- mu_tc_noise[id,,drop=FALSE]
    curDimNames <- list(paste0(colnames(X)[id], ";gene",gg),
                                paste0("celltype",letters[1:nCellTypes]))
    # simulate from Dirichlet.
    curalpha_gt <- rowMeans(sweep(mu_tc_id, 2, colSums(mu_tc_id), "/")) * magnitude_g[gg]
    alpha_gt[[gg]] <- curalpha_gt
    curmu_gtc <- sweep(sweep(mu_tc_id, 2, colSums(mu_tc_id), "/"), 2, mu_gc_sim[gg,], "*")
    dimnames(curmu_gtc) <- curDimNames
    curmu_gc <- colSums(curmu_gtc)
    stopifnot(identical(round(unname(curmu_gc),2), round(mu_gc_sim[gg,],2)))
    if(!dirichletNoise){
      # noiseless:
      curpi_gtc <- sweep(curmu_gtc, 2, curmu_gc, "/")
    } else {
      # dirichlet noise:
      curpi_gtc <- rdirichlet(n=nCellTypes, alpha=curalpha_gt)
      if(length(id) > 1) curpi_gtc <- t(curpi_gtc)
      dimnames(curpi_gtc) <- curDimNames
    }
    if(gg == 1){
      mu_gtc <- curmu_gtc
      mu_gc <- curmu_gc
      pi_gtc <- curpi_gtc
    } else {
      mu_gtc <- rbind(mu_gtc, curmu_gtc)
      mu_gc <- rbind(mu_gc, curmu_gc)
      pi_gtc <- rbind(pi_gtc, curpi_gtc)
    }
  }
  rownames(mu_gc) <- paste0("gene",1:G)
  names(alpha_gt) <- paste0("gene",1:G)
 
  for(cc in 1:nCellTypes){
    curY <- matrix(rpois(n= nPerGroup * G, lambda=mu_gc_sim[,cc]),
                   nrow=nrow(mu_gc_sim), ncol= nPerGroup, byrow=FALSE)
    if(cc == 1){
      Y_igc <- curY
    } else {
      Y_igc <- cbind(Y_igc, curY)
    }
  }
  rownames(Y_igc) <- paste0("gene",1:G)

  return(list(Y=Y_igc,
              pi_gtc=pi_gtc,
              mu_tc=mu_tc,
              mu_tc_noise=mu_tc_noise,
              mu_gtc=mu_gtc,
              mu_gc=mu_gc,
              alpha_gt=alpha_gt,
              fcAll = fcAll,
              deTFs = deTFs
              ))
}
```




```{r}
library(rafalib)
set.seed(123)
logit = function(x) log(x/(1-x))
expit = function(x) exp(x)/(1+exp(x))
set.seed(13)
## simulation parameters
G <- 500 #nr of genes
nTF <- 80 #nr of TFs
nPerGroup <- 50 #number of cells per cell type
shape_mu_t <- 1
scale_mu_t <- 2
shape_lambda_gc <- 1
scale_lambda_gc <- 1
nCellTypes <- 5
ct <- factor(rep(letters[1:nCellTypes], each=nPerGroup))
design <- model.matrix(~-1 + ct)
seed <- 3
magnitude_g <- rep(100,G)

## simulate GRN as TF regulation matrix
X <- matrix(0, nrow=G, ncol=nTF)
for(gg in 1:nrow(X)){
  nGenes <- rbinom(n=1, size=30, prob=.05)
  while(nGenes == 0) nGenes <- rbinom(n=1, size=30, prob=.05)
  id <- sample(ncol(X), nGenes)
  X[cbind(gg,id)] <- 1
}
rownames(X) <- paste0("gene",1:G)
colnames(X) <- paste0("tf",1:nTF)
rafalib::mypar(mfrow=c(1,2))
barplot(table(rowSums(X)), main="By how many TFs is a gene regulated?")
barplot(table(colSums(X)), main="How many genes is a TF regulating?")


simRes <- simulateFromGRN_extended(X, 
                                 G=G, 
                                 nTF=nTF, 
                                 nPerGroup=nPerGroup, 
                                 shape_mu_t=shape_mu_t, 
                                 scale_mu_t=scale_mu_t,
                                 shape_lambda_gc=shape_lambda_gc,
                                 scale_lambda_gc=scale_lambda_gc,
                                 nCellTypes=nCellTypes, 
                                 seed=3,
                                 magnitude_g=magnitude_g)

## check: mu_tc * lambda_gc = mu_gtc = mu_gc * pi_gtc
## note that if prior=FALSE, these are exactly the same!
## so there's only just some random noise.
mu_tc_sim <- simRes$mu_tc
mu_gc_sim <- simRes$mu_gc
pi_gtc_sim <- simRes$pi_gtc
mu_gtc_sim <- simRes$mu_gtc

# check mu_gc
mypar(mfrow=c(2,2))
plot(x=simRes$mu_gc[,1], y=rowMeans(simRes$Y[,1:50])) ; abline(0,1,col="red")
plot(x=simRes$mu_gc[,2], y=rowMeans(simRes$Y[,51:100])) ; abline(0,1,col="red")
smoothScatter(x=simRes$mu_gc[,1], y=rowMeans(simRes$Y[,1:50])) ; abline(0,1,col="red")
smoothScatter(x=simRes$mu_gc[,2], y=rowMeans(simRes$Y[,51:100])) ; abline(0,1,col="red")

```

# True GRN

```{r}
ct <- factor(rep(letters[1:nCellTypes], each=nPerGroup))
design <- model.matrix(~ -1 + ct)

alpha <- X
for(rr in 1:length(simRes$alpha_gt)){
  idGene <- names(simRes$alpha_gt)[rr]
  if(is.na(simRes$alpha_gt[[rr]][1])) next
  if(is.null(dim(simRes$alpha_gt[[rr]]))){
    # non DE
    idTF <- names(simRes$alpha_gt[[rr]])
    alpha[cbind(idGene,idTF)] <- simRes$alpha_gt[[rr]]
  } else {
    # DE
    idTF <- rownames(simRes$alpha_gt[[rr]])
    alpha[cbind(idGene,idTF)] <- rowMeans(simRes$alpha_gt[[rr]]) * 100
  }
}
# get true alpha for noisy GRN
# alphaTrueNoisy <- cbind(alpha, XNoisy[,(ncol(X)+1):(ncol(X)+nNoiseTFs)])

### regulon object for viper
tfAll <- unlist(mapply(rep, colnames(X), each=colSums(X)))
targetAll <- rownames(X)[unlist(apply(X,2, function(x) which(x > 0)))]
alphaAll <- alpha[X>0] / max(alpha)
dfReg <- data.frame(tf=tfAll,
                 target=targetAll,
                 mor=1,
                 likelihood=alphaAll)
dfReg <- dfReg[!duplicated(dfReg),]
dfReg$tf <- as.character(dfReg$tf)
dfReg$target <- as.character(dfReg$target)
regulon <- dorothea:::df2regulon(dfReg)

### genesets object for AUCell
genesets = dfReg %>%
  group_by(tf) %>%
  summarise(geneset = list(GSEABase::GeneSet(target))) %>%
  transmute(tf, geneset2 = pmap(., .f=function(tf, geneset, ...) {
    setName(geneset) = tf
    return(geneset)
  })) %>%
  deframe() %>%
  GeneSetCollection()

### truth object
truth <- simRes$fcAll
truth[simRes$fcAll == 1] <- FALSE
truth[simRes$fcAll != 1] <- TRUE

source('20201120_evaluateSimulatedDataset.R')
```

# Adding noise to GRN

## MSE for one dataset

```{r}
nNoiseTFGrid <- c(0, ncol(X), ncol(X)*2, ncol(X)*4) # 100% to 33.3% data-generating TFs
nNoiseEdgeGrid <- c(-sum(X)/2, -sum(X)/4, 0, sum(X)*2, sum(X)*4) # -50% to +200% true links
# nNoiseTFGrid <- c(ncol(X)*2, ncol(X)*4) # 100% to 33.3% data-generating TFs
# nNoiseEdgeGrid <- c(sum(X)*2, sum(X)*4) # -50% to +200% true links

mseList <- allResList <- list()
for(nnTF in 1:length(nNoiseTFGrid)){
  nNoiseTFs <- nNoiseTFGrid[nnTF]
  for(nnEdge in 1:length(nNoiseEdgeGrid)){
    set.seed(nnEdge)
    
    nNoiseEdges <- nNoiseEdgeGrid[nnEdge]
    
    XTrue <- X
    XNoisy <- addNoiseToGRN(X = XTrue,
                        nNoiseTFs = nNoiseTFs,
                        nNoiseEdges = nNoiseEdges,
                        noiseProb = 3/nrow(X))
    # truth
    truthNoisy <- simRes$fcAll
    truthNoisy[simRes$fcAll == 1] <- FALSE
    truthNoisy[simRes$fcAll != 1] <- TRUE
    truthNoisy <- rbind(truthNoisy, matrix(rep(FALSE, nNoiseTFs * ncol(simRes$fcAll)),
                                           nrow = nNoiseTFs, ncol=ncol(simRes$fcAll)))
    
    ## filter if necessary
    keepGene <- rowSums(XNoisy) > 0
    counts <- simRes$Y[keepGene,]
    curAlpha <- alpha[keepGene,]
    XNoisy <- XNoisy[keepGene,]
    keepTF <- colSums(XNoisy) > 0
    truthNoisy <- truthNoisy[keepTF,]
    
    # get true alpha for noisy GRN
    if(nNoiseTFs > 0){
      alphaTrueNoisy <- cbind(curAlpha, XNoisy[,(ncol(X)+1):(ncol(X)+nNoiseTFs)])
    } else {
      alphaTrueNoisy <- curAlpha
    }
    XNoisy <- XNoisy[,keepTF]
    alphaTrueNoisy <- alphaTrueNoisy[,keepTF]
    alphaTrueNoisy[XNoisy == 0] <- 0
    rownames(truthNoisy) <- colnames(XNoisy)
    
    simEvalNoise <- evaluateSimulation_noRepressions_MSE(counts = counts,
                                                     design = design,
                                                     XNoisy = XNoisy,
                                                     simRes = simRes,
                                                     alpha = alphaTrueNoisy,
                                                    truth = truthNoisy,
                                                    alphaScale = 1,
                                                    XTrue = XTrue,
                                                    nNoiseEdges = nNoiseEdges)
    simEvalNoise$nNoiseTF <- nNoiseTFGrid[nnTF]
    simEvalNoise$nNoiseEdge <- nNoiseEdgeGrid[nnEdge]
    mseList[[(nnTF-1)*(length(nNoiseEdgeGrid)) + nnEdge]] <- simEvalNoise
    
    allRes <- evaluateSimulation_noRepressions_MSE(counts = counts,
                                                     design = design,
                                                     XNoisy = XNoisy,
                                                     simRes = simRes,
                                                     alpha = alphaTrueNoisy,
                                                    truth = truthNoisy,
                                                    alphaScale = 1,
                                                   XTrue = XTrue,
                                                   nNoiseEdges = nNoiseEdges,
                                                   returnMutc = TRUE)
    allResList[[(nnTF-1)*(length(nNoiseEdgeGrid)) + nnEdge]] <- allRes
    
    tfNames <- rownames(simRes$mu_tc)
    sharedTF <- intersect(tfNames, rownames(allRes$allEdges$poisson))
    if(nNoiseEdges > 0){
      muDfTrueEdges <- data.frame(tf=sharedTF,
                 trueMu=simRes$mu_tc[sharedTF,1],
                 poisson=allRes$onlyTrueEdges$poisson[sharedTF,1],
                 dirMult=allRes$onlyTrueEdges$dirMult[sharedTF,1],
                 dirMult_alphaEst=allRes$onlyTrueEdges$dirMult_alphaEst[sharedTF,1],
                 poisson_lasso=allRes$onlyTrueEdges$poisson_lasso[sharedTF,1],
                 dirMult_lasso=allRes$onlyTrueEdges$dirMult_lasso[sharedTF,1],
                 dirMult_aphaEst_lasso=allRes$onlyTrueEdges$dirMult_lasso_alphaEst[sharedTF,1])
      # ## pivot to long format
      muDfLongTrueEdges <- pivot_longer(muDfTrueEdges, cols=colnames(muDfTrueEdges)[-c(1:2)],
                    names_to="method")
       muDfLongTrueEdges$noiseTF <- nNoiseTFs
       muDfLongTrueEdges$noiseEdge <- nNoiseEdges
       if(nnTF==1 & nnEdge==4){ ## first time with false positive edges in the loops
          muDfAll_trueEdges <- muDfLongTrueEdges
        } else {
          muDfAll_trueEdges <- rbind(muDfAll_trueEdges,muDfLongTrueEdges)
        }
    }
    
    sharedTF <- intersect(tfNames, rownames(allRes$allEdges$poisson))
    muDfAllEdges <- data.frame(tf=sharedTF,
                 trueMu=c(simRes$mu_tc[sharedTF,]),
                 poisson=c(allRes$allEdges$poisson[sharedTF,]),
                 dirMult=c(allRes$allEdges$dirMult[sharedTF,]),
                 dirMult_alphaEst=c(allRes$allEdges$dirMult_alphaEst[sharedTF,]),
                 poisson_lasso=c(allRes$allEdges$poisson_lasso[sharedTF,]),
                 dirMult_lasso=c(allRes$allEdges$dirMult_lasso[sharedTF,]),
                 dirMult_aphaEst_lasso=c(allRes$allEdges$dirMult_lasso_alphaEst[sharedTF,]))
    ## pivot to long format
    muDfLongAllEdges <- pivot_longer(muDfAllEdges, cols=colnames(muDfAllEdges)[-c(1:2)],
                 names_to="method")
    ## add edge and TF info
    muDfLongAllEdges$noiseTF <- nNoiseTFs
    muDfLongAllEdges$noiseEdge <- nNoiseEdges
    
    if(nnTF==1 & nnEdge==1){
      muDfAll_allEdges <- muDfLongAllEdges
    } else {
      muDfAll_allEdges <- rbind(muDfAll_allEdges,muDfLongAllEdges)
    }
  }
}

mseDf <- do.call(rbind, mseList)

ggplot(mseDf, aes(x=method, y=mse, col=method, shape=onlyTrue)) +
  geom_point() +
  theme_classic() +
  facet_wrap(nNoiseTF ~ nNoiseEdge) #+ ylim(c(0,4))

allMethods <- unique(muDfAll_allEdges$method)
pMethodList <- list()
pMethodMAList <- list()
for(mm in 1:length(allMethods)){
  curMethod <- allMethods[mm]
  curDf <- muDfAll_allEdges[muDfAll_allEdges$method == curMethod,]
  pMethod <- ggplot(curDf, aes(x=trueMu, y=value)) +
    geom_point(size=1/2) +
    geom_abline(intercept=0, slope=1, col="red") +
    facet_grid(noiseTF ~ noiseEdge) +
    theme_classic() +
    xlab("True value") +
    ylab("Estimated value") +
    ggtitle(curMethod) #+ xlim(c(0,8)) + ylim(c(0,8))
  pMethodMA <- ggplot(curDf, aes(x=(trueMu+value)/2, y=log(value/trueMu))) +
    geom_point(size=1/2) +
    geom_abline(intercept=0, slope=0, col="red") +
    facet_grid(noiseTF ~ noiseEdge) +
    theme_classic() +
    xlab("Mean") +
    ylab("Log difference (estimated/true)") +
    ggtitle(curMethod) +
    ylim(c(-5,5))
  pMethodList[[mm]] <- pMethod
  pMethodMAList[[mm]] <- pMethodMA

}

pMethodList
pMethodMAList

```

# MSE for 6 datasets in each setting.

```{r, eval=TRUE}
nNoiseTFGrid <- c(0, ncol(X), ncol(X)*2, ncol(X)*4) # 100% to 33.3% data-generating TFs
nNoiseEdgeGrid <- c(-sum(X)/2, -sum(X)/4, 0, sum(X)*2, sum(X)*4) # -50% to +200% true links
nIter <- 6

pNoLeg <- list()
for(nn in 1:nIter){
  set.seed(nn)
  for(nnTF in 1:length(nNoiseTFGrid)){
    nNoiseTFs <- nNoiseTFGrid[nnTF]
    for(nnEdge in 1:length(nNoiseEdgeGrid)){
      nNoiseEdges <- nNoiseEdgeGrid[nnEdge]

      
    
      nNoiseEdges <- nNoiseEdgeGrid[nnEdge]
      
      XTrue <- X
      XNoisy <- addNoiseToGRN(X = XTrue,
                          nNoiseTFs = nNoiseTFs,
                          nNoiseEdges = nNoiseEdges,
                          noiseProb = 3/nrow(X))
      # truth
      truthNoisy <- simRes$fcAll
      truthNoisy[simRes$fcAll == 1] <- FALSE
      truthNoisy[simRes$fcAll != 1] <- TRUE
      truthNoisy <- rbind(truthNoisy, matrix(rep(FALSE, nNoiseTFs * ncol(simRes$fcAll)),
                                             nrow = nNoiseTFs, ncol=ncol(simRes$fcAll)))
      
      ## filter if necessary
      keepGene <- rowSums(XNoisy) > 0
      counts <- simRes$Y[keepGene,]
      curAlpha <- alpha[keepGene,]
      XNoisy <- XNoisy[keepGene,]
      keepTF <- colSums(XNoisy) > 0
      truthNoisy <- truthNoisy[keepTF,]
      
      # get true alpha for noisy GRN
      if(nNoiseTFs > 0){
        alphaTrueNoisy <- cbind(curAlpha, XNoisy[,(ncol(X)+1):(ncol(X)+nNoiseTFs)])
      } else {
        alphaTrueNoisy <- curAlpha
      }
      XNoisy <- XNoisy[,keepTF]
      alphaTrueNoisy <- alphaTrueNoisy[,keepTF]
      alphaTrueNoisy[XNoisy == 0] <- 0
      rownames(truthNoisy) <- colnames(XNoisy)
      
      simEvalNoise <- evaluateSimulation_noRepressions_MSE(counts = counts,
                                                       design = design,
                                                       XNoisy = XNoisy,
                                                       simRes = simRes,
                                                       alpha = alphaTrueNoisy,
                                                      truth = truthNoisy,
                                                      alphaScale = 1,
                                                      XTrue = XTrue,
                                                      nNoiseEdges = nNoiseEdges)
      simEvalNoise$nNoiseTF <- nNoiseTFGrid[nnTF]
      simEvalNoise$nNoiseEdge <- nNoiseEdgeGrid[nnEdge]
      simEvalNoise$dataset <- nn
      mseList[[(nnTF-1)*(length(nNoiseEdgeGrid)) + nnEdge]] <- simEvalNoise
      
      allRes <- evaluateSimulation_noRepressions_MSE(counts = counts,
                                                       design = design,
                                                       XNoisy = XNoisy,
                                                       simRes = simRes,
                                                       alpha = alphaTrueNoisy,
                                                      truth = truthNoisy,
                                                      alphaScale = 1,
                                                     XTrue = XTrue,
                                                     nNoiseEdges = nNoiseEdges,
                                                     returnMutc = TRUE)
      allResList[[(nnTF-1)*(length(nNoiseEdgeGrid)) + nnEdge]] <- allRes
      
      tfNames <- rownames(simRes$mu_tc)
      sharedTF <- intersect(tfNames, rownames(allRes$allEdges$poisson))
      if(nNoiseEdges > 0){
        muDfTrueEdges <- data.frame(tf=sharedTF,
                   trueMu=c(simRes$mu_tc[sharedTF,]),
                   poisson=c(allRes$onlyTrueEdges$poisson[sharedTF,]),
                   dirMult=c(allRes$onlyTrueEdges$dirMult[sharedTF,]),
                   dirMult_alphaEst=c(allRes$onlyTrueEdges$dirMult_alphaEst[sharedTF,]),
                   poisson_lasso=c(allRes$onlyTrueEdges$poisson_lasso[sharedTF,]),
                   dirMult_lasso=c(allRes$onlyTrueEdges$dirMult_lasso[sharedTF,]),
                   dirMult_aphaEst_lasso=c(allRes$onlyTrueEdges$dirMult_lasso_alphaEst[sharedTF,]))
        # ## pivot to long format
        muDfLongTrueEdges <- pivot_longer(muDfTrueEdges, cols=colnames(muDfTrueEdges)[-c(1:2)],
                      names_to="method")
         muDfLongTrueEdges$noiseTF <- nNoiseTFs
         muDfLongTrueEdges$noiseEdge <- nNoiseEdges
         muDfLongTrueEdges$dataset <- nn
         if(nnTF==1 & nnEdge==4 & nn==1){ ## first time with false positive edges in the loops
            muDfAll_trueEdges <- muDfLongTrueEdges
          } else {
            muDfAll_trueEdges <- rbind(muDfAll_trueEdges,muDfLongTrueEdges)
          }
      }
      
      sharedTF <- intersect(tfNames, rownames(allRes$allEdges$poisson))
      muDfAllEdges <- data.frame(tf=sharedTF,
                   trueMu=c(simRes$mu_tc[sharedTF,]),
                   poisson=c(allRes$allEdges$poisson[sharedTF,]),
                   dirMult=c(allRes$allEdges$dirMult[sharedTF,]),
                   dirMult_alphaEst=c(allRes$allEdges$dirMult_alphaEst[sharedTF,]),
                   poisson_lasso=c(allRes$allEdges$poisson_lasso[sharedTF,]),
                   dirMult_lasso=c(allRes$allEdges$dirMult_lasso[sharedTF,]),
                   dirMult_aphaEst_lasso=c(allRes$allEdges$dirMult_lasso_alphaEst[sharedTF,]))
      ## pivot to long format
      muDfLongAllEdges <- pivot_longer(muDfAllEdges, cols=colnames(muDfAllEdges)[-c(1:2)],
                   names_to="method")
      ## add edge and TF info
      muDfLongAllEdges$noiseTF <- nNoiseTFs
      muDfLongAllEdges$noiseEdge <- nNoiseEdges
      muDfLongAllEdges$dataset <- nn
      
      if(nnTF==1 & nnEdge==1 & nn==1){
        muDfAll_allEdges <- muDfLongAllEdges
      } else {
        muDfAll_allEdges <- rbind(muDfAll_allEdges,muDfLongAllEdges)
      }
       
    }
  }
  if(nn == 1){
         mseListAll <- mseList
  } else {
      mseListAll <- c(mseListAll, mseList)
  }
}

date <- Sys.Date()
date <- gsub(x=date, pattern="-", replacement="")
saveRDS(mseListAll, file=paste0("../objects/mseListAll",date,".rds"))
saveRDS(muDfAll_allEdges, file=paste0("../objects/muDfAll_allEdges",date,".rds"))
saveRDS(muDfAll_trueEdges, file=paste0("../objects/muDfAll_trueEdges",date,".rds"))

```

## Graphic evaluation

### Based on all edges

```{r}
# muDfAll_allEdges <- readRDS("../objects/muDfAll_allEdges20230407.rds")
muDfAll_allEdges <- readRDS(paste0("../objects/muDfAll_allEdges",date,".rds"))

allMethods <- unique(muDfAll_allEdges$method)
pMethodList <- list()
pMethodMAList <- list()
for(mm in 1:length(allMethods)){
  curMethod <- allMethods[mm]
  curDf <- muDfAll_allEdges[muDfAll_allEdges$method == curMethod,]
  pMethod <- ggplot(curDf, aes(x=trueMu, y=value, col=dataset)) +
    geom_point(size=1/2) +
    geom_abline(intercept=0, slope=1, col="red") +
    facet_grid(noiseTF ~ noiseEdge) +
    theme_classic() +
    xlab("True value") +
    ylab("Estimated value") +
    ggtitle(curMethod) #+ xlim(c(0,8)) + ylim(c(0,8))
  pMethodMA <- ggplot(curDf, aes(x=(trueMu+value)/2, y=log(value/trueMu), col=dataset)) +
    geom_point(size=1/2) +
    geom_abline(intercept=0, slope=0, col="red") +
    facet_grid(noiseTF ~ noiseEdge) +
    theme_classic() +
    xlab("Mean") +
    ylab("Log difference (estimated/true)") +
    ggtitle(curMethod) +
    ylim(c(-5,5))
  pMethodList[[mm]] <- pMethod
  pMethodMAList[[mm]] <- pMethodMA

}


pMethodList
pMethodMAList

```

### Based on only ture edges

```{r}
# muDfAll_trueEdges <- readRDS("../objects/muDfAll_trueEdges20230407.rds")
muDfAll_trueEdges <- readRDS(paste0("../objects/muDfAll_trueEdges",date,".rds"))


allMethods <- unique(muDfAll_trueEdges$method)
pMethodList <- list()
pMethodMAList <- list()
for(mm in 1:length(allMethods)){
  curMethod <- allMethods[mm]
  curDf <- muDfAll_trueEdges[muDfAll_trueEdges$method == curMethod,]
  pMethod <- ggplot(curDf, aes(x=trueMu, y=value, col=dataset)) +
    geom_point(size=1/2) +
    geom_abline(intercept=0, slope=1, col="red") +
    facet_grid(noiseTF ~ noiseEdge) +
    theme_classic() +
    xlab("True value") +
    ylab("Estimated value") +
    ggtitle(curMethod) #+ xlim(c(0,8)) + ylim(c(0,8))
  pMethodMA <- ggplot(curDf, aes(x=(trueMu+value)/2, y=log(value/trueMu), col=dataset)) +
    geom_point(size=1/2) +
    geom_abline(intercept=0, slope=0, col="red") +
    facet_grid(noiseTF ~ noiseEdge) +
    theme_classic() +
    xlab("Mean") +
    ylab("Log difference (estimated/true)") +
    ggtitle(curMethod) +
    ylim(c(-5,5))
  pMethodList[[mm]] <- pMethod
  pMethodMAList[[mm]] <- pMethodMA

}


pMethodList
pMethodMAList

```


### MSE

```{r}
mseListAll <- readRDS("../objects/mseListAll20241003.rds")
# mseListAll <- readRDS(paste0("../objects/mseListAll",date,".rds"))

dfMSEAll <- do.call(rbind, mseListAll)
dfMSEAll$method[dfMSEAll$method == "dirMult_alphaEst"] <- "dirMultEBayes"
dfMSEAll$method[dfMSEAll$method == "dirMult_lasso_alphaEst"] <- "dirMultEBayes_lasso"
dfMSEAll$method <- factor(dfMSEAll$method, levels = c("poisson", "poisson_lasso",
                                                      "dirMult", "dirMult_lasso",
                                                      "dirMultEBayes", "dirMultEBayes_lasso"))
dfMSEAll$noiseEdges <- round(dfMSEAll$nNoiseEdge)
dfMSEAll$noiseTFs <- round(dfMSEAll$nNoiseTF)
dfMSEAll_allEdges <- dfMSEAll[dfMSEAll$onlyTrue==FALSE,]
ggplot(dfMSEAll_allEdges, aes(x=method, y=mse)) +
  geom_boxplot(aes(col=method)) +
  facet_wrap(.~noiseTFs * noiseEdges,
             ncol = length(nNoiseEdgeGrid),
             nrow = length(nNoiseTFGrid)) +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_y_continuous(n.breaks=5) +
  xlab("") + ylab("MSE") +
  ylim(c(0,4.5)) +
  geom_hline(yintercept=0, lty=2)
ggsave("../../plots/domino/mseAllSettings.pdf", width=12, height=9)



ggplot(dfMSEAll, aes(x=method, y=mse, fill=onlyTrue)) +
  geom_boxplot(aes(col=method)) +
  facet_wrap(.~noiseTFs * noiseEdges,
             ncol = length(nNoiseEdgeGrid),
             nrow = length(nNoiseTFGrid)) +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_y_continuous(n.breaks=5) +
  xlab("") + ylab("MSE") +
  ylim(c(0,4.5)) +
  geom_hline(yintercept=0, lty=2)
```
