---
title: "tmp"
author: "Koen Van den Berge"
date: "9/14/2020"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Simulation functions

```{r}
library(matrixStats)
ksource <- function(x, ...) {
  library(knitr)
  source(purl(x, output = tempfile()), ...)
}
library(tidyverse)
library(viper)
library(AUCell)
library(tidyverse)
library(GSEABase)
library(transfactor)

simulateFromGRN_extended <- function(X, 
                                   G=500, 
                                   nTF=80,
                                   fracDETFs=0.25,
                                   nPerGroup=50,
                                   nCellTypes=5, 
                                   shape_mu_t=1, 
                                   scale_mu_t=2, 
                                   shape_lambda_gc=1,
                                   scale_lambda_gc=scale_lambda_gc,
                                   magnitude_g=rep(100, G),
                                   seed=3,
                                   dirichletNoise = FALSE){
  
  set.seed(seed)
 
  ### Simulate mu_tc
  mu_tc <- matrix(rgamma(n=nTF, shape=shape_mu_t, scale=scale_mu_t),
                nrow=nTF, ncol=nCellTypes, byrow=FALSE)
  ### add noise
  # mu_tc_noise <- mu_tc + matrix(rnorm(n=length(mu_tc), mean=mu_tc, sd=.5),
  #                               nrow=nTF, ncol=nCellTypes)
  # mu_tc_noise[mu_tc_noise <= 0] <- 1e-5
  mu_tc_noise <- mu_tc
  rownames(mu_tc) <- paste0("tf",1:nTF)
  rownames(mu_tc_noise) <- paste0("tf",1:nTF)
  
  ### simulate DE
  deTFs <- sample(nTF, size=nTF * fracDETFs)
  # simulate fold changes
  logFC <- log(rnorm(n=length(deTFs) * (nCellTypes-1), mean=2.5, sd=.3))
  # random sign
  x <- rbinom(n=length(deTFs) * (nCellTypes-1), size=1, prob=.5)
  # logFC <- log(rep(5, length(deTFs) * (nCellTypes-1)))
  # x <- rep(1, length(deTFs) * (nCellTypes-1))
  fcAll <- matrix(1, nrow = nTF, ncol = nCellTypes - 1)
  fcAll[deTFs, ] <- matrix(exp(ifelse(x == 1, 1, -1) * logFC),
                           nrow = length(deTFs), ncol = nCellTypes - 1)
  mu_tc_noise[, -1] <- mu_tc_noise[, -1] * fcAll

  ### mu_gc
  mu_gc_sim <- X %*% mu_tc_noise
  
  ### calculate mu_gtc, mu_gc
  alpha_gt <- list()
  for(gg in 1:G){
    id <- which(X[gg,] == 1)
    mu_tc_id <- mu_tc_noise[id,,drop=FALSE]
    curDimNames <- list(paste0(colnames(X)[id], ";gene",gg),
                                paste0("celltype",letters[1:nCellTypes]))
    # simulate from Dirichlet.
    curalpha_gt <- rowMeans(sweep(mu_tc_id, 2, colSums(mu_tc_id), "/")) * magnitude_g[gg]
    alpha_gt[[gg]] <- curalpha_gt
    curmu_gtc <- sweep(sweep(mu_tc_id, 2, colSums(mu_tc_id), "/"), 2, mu_gc_sim[gg,], "*")
    dimnames(curmu_gtc) <- curDimNames
    curmu_gc <- colSums(curmu_gtc)
    stopifnot(identical(round(unname(curmu_gc),2), round(mu_gc_sim[gg,],2)))
    if(!dirichletNoise){
      # noiseless:
      curpi_gtc <- sweep(curmu_gtc, 2, curmu_gc, "/")
    } else {
      # dirichlet noise:
      curpi_gtc <- rdirichlet(n=nCellTypes, alpha=curalpha_gt)
      if(length(id) > 1) curpi_gtc <- t(curpi_gtc)
      dimnames(curpi_gtc) <- curDimNames
    }
    if(gg == 1){
      mu_gtc <- curmu_gtc
      mu_gc <- curmu_gc
      pi_gtc <- curpi_gtc
    } else {
      mu_gtc <- rbind(mu_gtc, curmu_gtc)
      mu_gc <- rbind(mu_gc, curmu_gc)
      pi_gtc <- rbind(pi_gtc, curpi_gtc)
    }
  }
  rownames(mu_gc) <- paste0("gene",1:G)
  names(alpha_gt) <- paste0("gene",1:G)
 
  for(cc in 1:nCellTypes){
    curY <- matrix(rpois(n= nPerGroup * G, lambda=mu_gc_sim[,cc]),
                   nrow=nrow(mu_gc_sim), ncol= nPerGroup, byrow=FALSE)
    if(cc == 1){
      Y_igc <- curY
    } else {
      Y_igc <- cbind(Y_igc, curY)
    }
  }
  rownames(Y_igc) <- paste0("gene",1:G)

  return(list(Y=Y_igc,
              pi_gtc=pi_gtc,
              mu_tc=mu_tc,
              mu_tc_noise=mu_tc_noise,
              mu_gtc=mu_gtc,
              mu_gc=mu_gc,
              alpha_gt=alpha_gt,
              fcAll = fcAll,
              deTFs = deTFs
              ))
}
```




```{r}
library(rafalib)
set.seed(123)
logit = function(x) log(x/(1-x))
expit = function(x) exp(x)/(1+exp(x))
set.seed(13)
## simulation parameters
G <- 500 #nr of genes
nTF <- 80 #nr of TFs
nPerGroup <- 50 #number of cells per cell type
shape_mu_t <- 1
scale_mu_t <- 2
shape_lambda_gc <- 1
scale_lambda_gc <- 1
nCellTypes <- 5
ct <- factor(rep(letters[1:nCellTypes], each=nPerGroup))
design <- model.matrix(~-1 + ct)
seed <- 3
magnitude_g <- rep(100,G)

## simulate GRN as TF regulation matrix
X <- matrix(0, nrow=G, ncol=nTF)
for(gg in 1:nrow(X)){
  nGenes <- rbinom(n=1, size=30, prob=.05)
  while(nGenes == 0) nGenes <- rbinom(n=1, size=30, prob=.05)
  id <- sample(ncol(X), nGenes)
  X[cbind(gg,id)] <- 1
}
rownames(X) <- paste0("gene",1:G)
colnames(X) <- paste0("tf",1:nTF)
rafalib::mypar(mfrow=c(1,2))
barplot(table(rowSums(X)), main="By how many TFs is a gene regulated?")
barplot(table(colSums(X)), main="How many genes is a TF regulating?")


simRes <- simulateFromGRN_extended(X, 
                                 G=G, 
                                 nTF=nTF, 
                                 nPerGroup=nPerGroup, 
                                 shape_mu_t=shape_mu_t, 
                                 scale_mu_t=scale_mu_t,
                                 shape_lambda_gc=shape_lambda_gc,
                                 scale_lambda_gc=scale_lambda_gc,
                                 nCellTypes=nCellTypes, 
                                 seed=3,
                                 magnitude_g=magnitude_g)

## check: mu_tc * lambda_gc = mu_gtc = mu_gc * pi_gtc
## note that if prior=FALSE, these are exactly the same!
## so there's only just some random noise.
mu_tc_sim <- simRes$mu_tc
mu_gc_sim <- simRes$mu_gc
pi_gtc_sim <- simRes$pi_gtc
mu_gtc_sim <- simRes$mu_gtc

# check mu_gc
mypar(mfrow=c(2,2))
plot(x=simRes$mu_gc[,1], y=rowMeans(simRes$Y[,1:50])) ; abline(0,1,col="red")
plot(x=simRes$mu_gc[,2], y=rowMeans(simRes$Y[,51:100])) ; abline(0,1,col="red")
smoothScatter(x=simRes$mu_gc[,1], y=rowMeans(simRes$Y[,1:50])) ; abline(0,1,col="red")
smoothScatter(x=simRes$mu_gc[,2], y=rowMeans(simRes$Y[,51:100])) ; abline(0,1,col="red")

```

# True GRN

```{r}
ct <- factor(rep(letters[1:nCellTypes], each=nPerGroup))
design <- model.matrix(~ -1 + ct)

alpha <- X
for(rr in 1:length(simRes$alpha_gt)){
  idGene <- names(simRes$alpha_gt)[rr]
  if(is.na(simRes$alpha_gt[[rr]][1])) next
  if(is.null(dim(simRes$alpha_gt[[rr]]))){
    # non DE
    idTF <- names(simRes$alpha_gt[[rr]])
    alpha[cbind(idGene,idTF)] <- simRes$alpha_gt[[rr]]
  } else {
    # DE
    idTF <- rownames(simRes$alpha_gt[[rr]])
    alpha[cbind(idGene,idTF)] <- rowMeans(simRes$alpha_gt[[rr]]) * 100
  }
}
# get true alpha for noisy GRN
# alphaTrueNoisy <- cbind(alpha, XNoisy[,(ncol(X)+1):(ncol(X)+nNoiseTFs)])

### regulon object for viper
tfAll <- unlist(mapply(rep, colnames(X), each=colSums(X)))
targetAll <- rownames(X)[unlist(apply(X,2, function(x) which(x > 0)))]
alphaAll <- alpha[X>0] / max(alpha)
dfReg <- data.frame(tf=tfAll,
                 target=targetAll,
                 mor=1,
                 likelihood=alphaAll)
dfReg <- dfReg[!duplicated(dfReg),]
dfReg$tf <- as.character(dfReg$tf)
dfReg$target <- as.character(dfReg$target)
regulon <- dorothea:::df2regulon(dfReg)

### genesets object for AUCell
genesets = dfReg %>%
  group_by(tf) %>%
  summarise(geneset = list(GSEABase::GeneSet(target))) %>%
  transmute(tf, geneset2 = pmap(., .f=function(tf, geneset, ...) {
    setName(geneset) = tf
    return(geneset)
  })) %>%
  deframe() %>%
  GeneSetCollection()

### truth object
truth <- simRes$fcAll
truth[simRes$fcAll == 1] <- FALSE
truth[simRes$fcAll != 1] <- TRUE

# source('20201120_evaluateSimulatedDataset.R')
```


```{r}
poiRes <- transfactor::estimateActivity(counts = simRes$Y,
                              X = X,
                              U = design,
                              #alpha = alpha,
                              #alphaScale = 1,
                              model = "poisson")

drRes <- transfactor::estimateActivity(counts = simRes$Y,
                              X = X,
                              U = design,
                              alpha = alpha,
                              alphaScale = 1,
                              model = "dirMult")

```

